
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orxdsnvcykhyzzoizhxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yeGRzbnZjeWtoeXp6b2l6aHh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MzM0NzksImV4cCI6MjA1ODQwOTQ3OX0.IvcvtP9PkSlEhjaSBQWTay5-1mrDh8P8y11YxCcMrhE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
